/**
 * Visual regression: a small number of full-screen snapshots of the app's
 * key screens, compared pixel-by-pixel against a committed baseline image
 * on every CI run.
 *
 * Baselines are NOT generated by this sandbox's tooling - see
 * e2e/VISUAL_REGRESSION.md for why, and for the one-time command to
 * generate them. Until frontend/e2e/visual.spec.js-snapshots/ exists with
 * real baseline PNGs, these tests fail with "no baseline found" rather than
 * silently passing, which is the correct failure mode: it tells you
 * baselines are still missing rather than pretending the check ran.
 */
const { test, expect } = require('@playwright/test');
const { signIn } = require('./helpers');

test.describe('Visual regression', () => {
  test('sign-in screen', async ({ page }) => {
    await page.goto('/');
    await expect(page.getByPlaceholder('Email')).toBeVisible();
    // A small tolerance absorbs sub-pixel anti-aliasing noise between runs
    // without hiding a real layout or color regression.
    await expect(page).toHaveScreenshot('sign-in.png', { maxDiffPixelRatio: 0.02 });
  });

  test('garage dashboard with a vehicle selected', async ({ page }) => {
    await signIn(page);
    await page.goto('/');
    await expect(page.getByText('My Garage')).toBeVisible();
    await page.getByText('2020 Honda Civic').click();
    await expect(page.getByText('Add Service')).toBeVisible();
    await expect(page).toHaveScreenshot('garage-dashboard.png', { maxDiffPixelRatio: 0.02 });
  });
});
